### ISSUE TITLE
Keypress down moves table of markets down 2 items

### ISSUE THREAD

**Issue by aars** [Aaaaaashu/Whale#6]
I'm pretty sure this is related to using both `inquirer` and `blessed`, and I think `inquirer` is to blame, but I've been searching and debugging for a few hours now... So...

Can anyone confirm that pressing the down key once moves the markets list down 2 items? (only occurs when more than 2 markets are selected).

I know it doesn't happen when no prompts from `inquirer` are used (using PR #4, define a config with just one market and use `-a` option, this skips all questions, and results in a normal working blessed screen table)

**Comment by aars** [comment]
This is probably a hacky solution, but simply removing the data listener(s) before starting a blessed screen fixes this issue. I've put it in [`libs/prompt.js`](https://github.com/Aaaaaashu/Whale/pull/5/files#diff-b0766f40305d555e4a8c015a42c00e43R53) and it's part of PR #5.

**Comment by 0xashu** [comment]
Haha, I also encountered this problem, and have submitted issue https://github.com/SBoudrias/Inquirer.js/issues/477.

It took me a long time to solve, but no any result...
So very glad to see your hacky solution, and have merged your PR https://github.com/Aaaaaashu/Whale/pull/5
